name: Scrape Lightning Strikes

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Needed for committing changes to the repository

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium matplotlib cartopy
          sudo apt-get update
          sudo apt-get install -y libgeos-dev  # Required for Cartopy

      - name: Install Chrome and ChromeDriver
        run: |
          # Add Google Chrome repository and install Chrome
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg  # Modern keyring approach
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

          # Get Chrome version
          CHROME_VERSION=$(google-chrome --version | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")
          echo "Chrome version: $CHROME_VERSION"

          # Remove any existing ChromeDriver to avoid conflicts
          sudo rm -f /usr/local/bin/chromedriver

          # Fetch the latest ChromeDriver version for this Chrome major version
          DRIVER_MAJOR_VERSION=${CHROME_VERSION%%.*}
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${DRIVER_MAJOR_VERSION}.0" || echo "114.0.5735.90")
          if [ -z "$DRIVER_VERSION" ] || echo "$DRIVER_VERSION" | grep -q "<Error>"; then
            echo "No exact match for Chrome major version $DRIVER_MAJOR_VERSION. Falling back to 114.0.5735.90"
            DRIVER_VERSION="114.0.5735.90"
          fi
          echo "Using ChromeDriver version: $DRIVER_VERSION"

          # Download and install ChromeDriver
          wget -q "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip -o chromedriver_linux64.zip -d /tmp  # Overwrite without prompting
          sudo mv /tmp/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          # Verify installation
          INSTALLED_DRIVER_VERSION=$(chromedriver --version | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+")
          echo "Installed ChromeDriver version: $INSTALLED_DRIVER_VERSION"
          if ! echo "$INSTALLED_DRIVER_VERSION" | grep -q "^${DRIVER_MAJOR_VERSION}"; then
            echo "Warning: ChromeDriver version ($INSTALLED_DRIVER_VERSION) does not match Chrome major version ($DRIVER_MAJOR_VERSION). Proceeding anyway."
          fi

      - name: Run scraping script
        run: python scrape_and_plot.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add strikes.json worldwide_lightning_all_time.png
          git commit -m "Update lightning strikes data and plot" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
